#!/bin/bash

# Instalar dependencias
/usr/bin/npm install

# Construir la aplicación
/usr/bin/npm run build

# Iniciar el servidor en el puerto que Hostinger especifica
export PORT=3000
export HOST=0.0.0.0
/usr/bin/npm start